--DOWN
DROP TABLE IF EXISTS subtitulos;
--UP
CREATE TABLE subtitulos(
	id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	nombre	VARCHAR(30) NOT NULL,
  modulos INTEGER,
  FOREIGN KEY (modulos) REFERENCES modulos(id) ON DELETE CASCADE
)